# Generated by Django 2.2.8 on 2020-08-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('effect', models.TextField()),
                ('keyword', models.TextField()),
                ('rarity', models.CharField(blank=True, max_length=40)),
                ('score', models.PositiveSmallIntegerField()),
                ('opinion_count', models.PositiveSmallIntegerField()),
                ('card', models.BooleanField(default=False)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('cost', models.CharField(blank=True, max_length=10)),
                ('relic', models.BooleanField(default=False)),
                ('flavor_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('view', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('pro', models.PositiveSmallIntegerField(default=0)),
                ('con', models.PositiveSmallIntegerField(default=0)),
                ('archetype', models.BooleanField(default=False)),
                ('key_card', models.TextField()),
                ('key_relic', models.TextField()),
                ('recommend_card', models.TextField()),
                ('recommend_relic', models.TextField()),
                ('card_character', models.CharField(max_length=50)),
                ('relic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('eng_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('effect', models.TextField()),
                ('keyword', models.TextField()),
                ('rarity', models.TextField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cardrelic',
            constraint=models.UniqueConstraint(fields=('eng_name', 'subject', 'card'), name='unique_card'),
        ),
    ]
