# Generated by Django 2.2.8 on 2020-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelic',
            name='opinion_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
