# Generated by Django 2.2.8 on 2020-09-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='EMAIL ID.', max_length=64, unique=True),
        ),
    ]
