# Generated by Django 2.2.8 on 2020-06-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
