# Generated by Django 2.2.8 on 2020-06-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200605_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='view',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
