# Generated by Django 2.2.8 on 2020-09-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200911_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='pro_con_record',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
