# Generated by Django 2.2.8 on 2020-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200605_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('pro', models.PositiveSmallIntegerField(default=0)),
                ('con', models.PositiveSmallIntegerField(default=0)),
                ('archetype', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
