# Generated by Django 2.2.8 on 2020-09-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_opinion_pro_con_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='pro_con_record',
            new_name='pro_record',
        ),
        migrations.AddField(
            model_name='opinion',
            name='con_record',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
