# Generated by Django 2.2.8 on 2020-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200625_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='subject',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
