# Generated by Django 2.2.8 on 2020-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_opinion_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='archetype',
        ),
        migrations.AddField(
            model_name='opinion',
            name='recommend_card',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='recommend_relic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
