# Generated by Django 2.2.8 on 2020-09-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200925_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='con_record',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='pro_record',
        ),
    ]
