# Generated by Django 2.2.8 on 2020-09-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200926_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='con_record',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='pro_record',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
