# Generated by Django 2.2.8 on 2020-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200706_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='archetype',
            field=models.BooleanField(default=False),
        ),
    ]
