# Generated by Django 2.2.8 on 2020-07-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_opinion_archetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='archetype',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='recommend_card',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='recommend_relic',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='title',
        ),
    ]
