# Generated by Django 2.2.8 on 2020-07-07 14:12

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200706_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eng_name', models.CharField(max_length=50)),
                ('opinion', djongo.models.fields.ArrayField(model_container=api.models.Opinion)),
                ('img', models.ImageField(upload_to='')),
                ('effect', models.TextField()),
                ('keyword', models.TextField()),
                ('card', models.BooleanField(default=False)),
                ('rarity', models.TextField(max_length=20)),
                ('kind', models.TextField(max_length=20)),
                ('cost', models.PositiveSmallIntegerField()),
                ('relic', models.BooleanField(default=False)),
                ('flavor_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Opinion',
        ),
    ]
