# Generated by Django 2.2.8 on 2020-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200707_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('score', models.PositiveSmallIntegerField()),
                ('pro', models.PositiveSmallIntegerField(default=0)),
                ('con', models.PositiveSmallIntegerField(default=0)),
                ('archetype', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('recommend_card', models.TextField()),
                ('recommend_relic', models.TextField()),
            ],
        ),
    ]
