# Generated by Django 2.2.8 on 2020-07-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrelic',
            name='opinion',
        ),
    ]
