# Generated by Django 2.2.8 on 2020-07-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cardrelic_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='opinion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Opinion'),
        ),
    ]
