# Generated by Django 2.2.8 on 2020-07-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cardrelic_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrelic',
            name='opinion',
        ),
        migrations.AddField(
            model_name='opinion',
            name='card_relic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CardRelic'),
        ),
    ]
