# Generated by Django 2.2.8 on 2020-07-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200709_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='card_relic',
        ),
        migrations.DeleteModel(
            name='CardRelic',
        ),
    ]
