# Generated by Django 2.2.8 on 2020-07-09 14:07

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200709_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='keyword',
            field=djongo.models.fields.ArrayField(model_container=api.models.EffectKeyword, null=True),
        ),
    ]
