# Generated by Django 2.2.8 on 2020-07-21 22:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200721_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelic',
            fields=[
                ('eng_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('effect', models.TextField()),
                ('keyword', jsonfield.fields.JSONField()),
                ('card', models.BooleanField(default=False)),
                ('rarity', models.CharField(blank=True, max_length=20)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('cost', models.CharField(max_length=10)),
                ('relic', models.BooleanField(default=False)),
                ('flavor_text', models.TextField(blank=True)),
            ],
        ),
    ]
