# Generated by Django 2.2.8 on 2020-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cardrelic_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrelic',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='kind',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='rarity',
            field=models.CharField(max_length=20),
        ),
    ]
