# Generated by Django 2.2.8 on 2020-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cardrelic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
