# Generated by Django 2.2.8 on 2020-07-09 16:34

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200709_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='keyword',
            field=djongo.models.fields.ArrayField(default=False, model_container=api.models.EffectKeyword),
            preserve_default=False,
        ),
    ]
