# Generated by Django 2.2.8 on 2020-08-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cardrelic_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='title',
        ),
    ]
