# Generated by Django 2.2.8 on 2020-07-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cardrelic_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrelic',
            name='keyword',
        ),
    ]
