# Generated by Django 2.2.8 on 2020-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_opinion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='key_card',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinion',
            name='key_relic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
