# Generated by Django 2.2.8 on 2020-07-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cardrelic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardRelic',
        ),
    ]
