# Generated by Django 2.2.8 on 2020-08-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200806_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='eng_name',
            field=models.CharField(max_length=50),
        ),
    ]
