# Generated by Django 2.2.8 on 2020-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cardrelic_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelic',
            name='flavor_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cardrelic',
            name='rarity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
