# Generated by Django 2.2.8 on 2020-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200709_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='card_relic',
        ),
        migrations.AddField(
            model_name='cardrelic',
            name='subject',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
