# Generated by Django 2.2.8 on 2020-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200812_1630'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cardrelic',
            constraint=models.UniqueConstraint(fields=('eng_name', 'subject', 'card'), name='unique_card'),
        ),
    ]
