# Generated by Django 2.2.8 on 2020-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200812_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='card_character',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
