# Generated by Django 2.2.8 on 2020-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_opinion_card_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrelic',
            name='opinion_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
