# Generated by Django 2.2.8 on 2020-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_cardrelic_opinion_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelic',
            name='rarity',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
