# Generated by Django 2.2.8 on 2020-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200818_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelic',
            name='cost',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
