# Generated by Django 2.2.8 on 2020-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200818_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='relic',
            field=models.BooleanField(default=False),
        ),
    ]
